#!/usr/bin/env pwsh

$ErrorActionPreference = "Stop"

& pwsh -NoProfile -ExecutionPolicy Bypass -File "./tools/Validate-RuntimeDocumentation.ps1"
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

exit 0
